"""Email sender — attaches the Excel workbook via Gmail SMTP."""

import os
import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from .config import EMAIL_CONFIG, EXCEL_FILE, SITE_SHEET_NAMES, TODAY


def send_email(new_listings: list[dict]) -> None:
    """Send the Excel workbook via Gmail SMTP."""
    if not EMAIL_CONFIG["enabled"]:
        print("\n  ✉ Email disabled in config, skipping.")
        return

    by_source = {}
    for listing in new_listings:
        by_source.setdefault(listing["source"], []).append(listing)

    # Build HTML body
    site_rows = ""
    for site_name in SITE_SHEET_NAMES:
        count = len(by_source.get(site_name, []))
        site_rows += (
            f"<tr>"
            f"<td style='padding:6px 12px;border:1px solid #ddd;'>{site_name}</td>"
            f"<td style='padding:6px 12px;border:1px solid #ddd;text-align:center;'>{count}</td>"
            f"</tr>\n"
        )

    html_body = f"""\
<html>
<body style="font-family:Arial,sans-serif;color:#333;">
  <h2 style="color:#1F3864;">🏠 NYC Apartment Listings — {TODAY}</h2>
  <p>Found <strong>{len(new_listings)}</strong> new listing(s) today.</p>
  <table style="border-collapse:collapse;margin:16px 0;">
    <tr style="background:#1F3864;color:white;">
      <th style="padding:8px 12px;border:1px solid #ddd;">Site</th>
      <th style="padding:8px 12px;border:1px solid #ddd;">New Listings</th>
    </tr>
    {site_rows}
  </table>
  <p style="color:#548235;">
    💡 New listings are highlighted
    <span style="background:#E2EFDA;padding:2px 6px;">green</span>
    in the attached Excel file.
  </p>
  <p style="font-size:0.9em;color:#888;">Generated by Apartment Hunter</p>
</body>
</html>"""

    msg = MIMEMultipart()
    msg["From"] = EMAIL_CONFIG["from"]
    msg["To"] = ", ".join(EMAIL_CONFIG["to"])
    msg["Subject"] = EMAIL_CONFIG["subject"].format(date=TODAY)
    msg.attach(MIMEText(html_body, "html"))

    # Attach Excel file
    if os.path.exists(EXCEL_FILE):
        with open(EXCEL_FILE, "rb") as f:
            part = MIMEApplication(f.read(), Name=EXCEL_FILE)
        part["Content-Disposition"] = f'attachment; filename="{EXCEL_FILE}"'
        msg.attach(part)

    try:
        with smtplib.SMTP(EMAIL_CONFIG["smtp_host"], EMAIL_CONFIG["smtp_port"]) as server:
            server.starttls()
            server.login(EMAIL_CONFIG["from"], EMAIL_CONFIG["password"])
            server.sendmail(EMAIL_CONFIG["from"], EMAIL_CONFIG["to"], msg.as_string())
        print(f"  ✓ Email sent to {', '.join(EMAIL_CONFIG['to'])}")
    except smtplib.SMTPAuthenticationError:
        print(
            "\n  ✘ Email authentication failed!"
            "\n    Use a Gmail App Password (not your regular password)."
            "\n    Generate one at: https://myaccount.google.com/apppasswords"
        )
    except Exception as e:
        print(f"\n  ✘ Email failed: {e}")
